#!/usr/bin/env bash

set -e

ROOT=$(dirname "${BASH_SOURCE}")
source ${ROOT}/.env

mkdir -p ${HOME}/temp
touch ${HOME}/temp/.zsh_history
touch ${HOME}/.tool-versions
mkdir -p ${HOME}/secrets
mkdir -p ${HOME}/.vim
mkdir -p ${HOME}/.gnupg
mkdir -p ${HOME}/.asdf
mkdir -p ${HOME}/.local/share
mkdir -p ${HOME}/.bp
mkdir -p ${HOME}/.krew

exec docker run \
    --rm \
    -d \
    --name devbox \
    --hostname="$(hostname)" \
    --privileged \
    --net=macvlan4to6 \
    --ip ${CONTAINER_IPV4} \
    --ip6 ${CONTAINER_IPV6} \
    -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /lib/modules:/lib/modules \
    -v /dev:/dev \
    -v /usr/share/ca-certificates:/usr/share/ca-certificates \
    -v /etc/ssl/certs:/etc/ssl/certs \
    -v ${HOME}/src:/home/dev/src \
    -v ${HOME}/pkg:/home/dev/pkg \
    -v ${HOME}/secrets:/home/dev/secrets \
    -v ${HOME}/.config:/home/dev/.config \
    -v ${HOME}/.local/share:/home/dev/.local/share \
    -v ${HOME}/.kube:/home/dev/.kube \
    -v ${HOME}/.docker:/home/dev/.docker \
    -v ${HOME}/temp/.zsh_history:/home/dev/.zsh_history \
    -v ${HOME}/.vim:/home/dev/.vim \
    -v ${HOME}/.gnupg:/home/dev/.gnupg \
    -v ${HOME}/.asdf:/home/dev/.asdf \
    -v ${HOME}/.tool-versions:/home/dev/.tool-versions \
    -v ${HOME}/shared:/home/dev/nfs \
    -v ${HOME}/old:/home/dev/old \
    -v ${HOME}/.bp:/home/dev/.bp \
    -v ${HOME}/.krew:/home/dev/.krew \
    -w /home/dev \
    yuanying/devbox
