#!/usr/bin/env bash

set -e

ROOT=$(dirname "${BASH_SOURCE}")

exec docker run \
    --rm \
    -d \
    --name devbox \
    --hostname="$(hostname)" \
    --privileged \
    -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /lib/modules:/lib/modules \
    -v /dev:/dev \
    -v /usr/share/ca-certificates:/usr/share/ca-certificates \
    -v /etc/ssl/certs:/etc/ssl/certs \
    --mount type=bind,source=/home/yuanying,target=/home/yuanying,bind-propagation=slave \
    -w /home/yuanying \
    -p 8080:8080 \
    -p 9090:9090 \
    -p 3222:3222 \
    -p 60000-60010:60000-60010/udp \
    yuanying/devbox
