#!/usr/bin/env bash

set -e

mkdir -p /home/$USER/temp
touch /home/$USER/temp/.zsh_history
mkdir -p /home/$USER/.rbenv
mkdir -p /home/$USER/.pyenv
mkdir -p /home/$USER/secrets

exec docker run \
    --rm \
    -d \
    --name devbox \
    --cap-add SYS_PTRACE \
    --network host \
    -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /home/$USER/src:/home/dev/src \
    -v /home/$USER/secrets:/home/dev/secrets \
    -v /home/$USER/.kube:/home/dev/.kube \
    -v /home/$USER/temp/.zsh_history:/home/dev/.zsh_history \
    -v /home/$USER/.rbenv:/home/dev/.rbenv \
    -v /home/$USER/.pyenv:/home/dev/.pyenv \
    -w /home/dev \
    -p 3222:3222 \
    -p 60000-60010:60000-60010/udp \
    yuanying/devbox
